platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TSwiftCore_Example' do
  pod 'TSwiftCore', :path => '../'

  target 'TSwiftCore_Tests' do
    inherit! :search_paths

    
  end
end
